version: "3"
services:
    php:
        container_name: php
        image: thalfm/php:7.1
        build:
            context: .
        volumes:
            - ./blog:/app
        depends_on:
          - composer
    web:
        container_name: webserver
        image: "nginx:1.13.8-alpine"
        volumes:
            - ./blog:/app/
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - php
            - database
    composer:
        container_name: composer
        image: thalfm/composer
        build:
          context: .
        volumes:
          - ./blog:/app
    database:
        container_name: database
        restart: always
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: blog
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - ./database:/var/lib/postgresql