version: "3"
services:
  php:
    container_name: php
    image: thalfm/php:7.1
    build:
      dockerfile: ./docker/php
      context: .
    volumes:
      - ./shop:/app
    networks:
      - development-network
    depends_on:
      - pgsql
  web:
    container_name: webserver
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./shop:/app/
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8010:80"
    depends_on:
      - php
    networks:
      - development-network
  pgsql:
    container_name: pgsql
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - development-network
networks:
  development-network:
    driver: bridge
volumes:
  pgdata:
    driver: local